import { Joi, celebrate, Segments } from "celebrate";
import joiObjectid from "joi-objectid";

// This shouldn't run multiple times.
Joi.objectId = joiObjectid(Joi);

// User ID is generated by firebase, not NongoDB objectId
const id = Joi.string().required();
const name = Joi.string().required();
const email = Joi.string().email().required();

const postRegisterPattern = Joi.object({
  id,
  name,
  email,
});

const postLoginPattern = Joi.object({
  id,
});


const postRegisterCelebrate = celebrate({ [Segments.BODY]: postRegisterPattern });
const postLoginCelebrate = celebrate({ [Segments.BODY]: postLoginPattern });

export {
  postRegisterCelebrate,
  postLoginCelebrate,
};
